#!/bin/bash

if [ $# -ne 2 ]; then
   >&2 echo "incorrect number of command line arguments"
   exit 1
fi

test_suite=$1
program=$2

while read -r line
do
   if [ ! -f ${line}.in ]; then
      >&2 echo "${line}.in does not exist"
      exit 1
   fi

   if [ ! -r ${line}.in ]; then
      >&2 echo "${line}.in is not readable"
      exit 1
   fi   

   if [ ! -f ${line}.out ]; then
      >&2 echo "${line}.out does not exist"
      exit 1
   fi

   if [ ! -r ${line}.out ]; then
      >&2 echo "${line}.out is not readable"
      exit 1
   fi

   input_file=${line}.in
   output_file=${line}.out

   program_input=$(cat $input_file)
   expected_output=$(cat $output_file)

   if [ ! -f ${line}.args ]; then
      program_output=$($program < $input_file)
   else
      if [ ! -r ${line}.args ]; then
         >&2 echo "${line}.args is not readable"
         exit 1
      fi
      arg_file=${line}.args
      program_args=$(cat $arg_file)
      program_output=$($program $program_args < $input_file)
   fi

   diff <(echo $program_output) <(echo $expected_output) > /dev/null
   if [ $? -ne 0 ]; then
         echo -e "Test failed: ${line}"
         echo -e "Input:\n$program_input"
         echo -e "Expected:\n$expected_output"
         echo -e "Actual:\n$program_output\n"
   fi
done < $test_suite
